package li.drizz.app.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * drizz.li's warm palette, converted from its oklch tokens
 * (primary oklch(0.65 0.17 55) → #DB6C00). Used when dynamic color is off or
 * unavailable; dynamic (Material You) schemes take priority on Android 12+.
 */
val SeedPrimary = Color(0xFFDB6C00)

val LightPrimary = Color(0xFF9A4A00)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDBC7)
val LightOnPrimaryContainer = Color(0xFF341100)
val LightSecondary = Color(0xFF765848)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDCCB)
val LightOnSecondaryContainer = Color(0xFF2B160A)
val LightTertiary = Color(0xFF616038)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFE7E5BB)
val LightOnTertiaryContainer = Color(0xFF1D1D00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFAF9F7)
val LightOnBackground = Color(0xFF221B15)
val LightSurface = Color(0xFFFAF9F7)
val LightOnSurface = Color(0xFF221B15)
val LightSurfaceVariant = Color(0xFFF3EDE7)
val LightOnSurfaceVariant = Color(0xFF52443B)
val LightOutline = Color(0xFF847469)
val LightOutlineVariant = Color(0xFFD6C3B6)
val LightSurfaceDim = Color(0xFFDED8D2)
val LightSurfaceBright = Color(0xFFFAF9F7)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF5F2EF)
val LightSurfaceContainer = Color(0xFFEFEBE7)
val LightSurfaceContainerHigh = Color(0xFFE9E5E1)
val LightSurfaceContainerHighest = Color(0xFFE3DFDB)
val LightInverseSurface = Color(0xFF382E27)
val LightInverseOnSurface = Color(0xFFFCEEE3)
val LightInversePrimary = Color(0xFFFFB784)

val DarkPrimary = Color(0xFFFFB784)
val DarkOnPrimary = Color(0xFF512500)
val DarkPrimaryContainer = Color(0xFF733700)
val DarkOnPrimaryContainer = Color(0xFFFFDBC7)
val DarkSecondary = Color(0xFFE5BFA9)
val DarkOnSecondary = Color(0xFF432B1C)
val DarkSecondaryContainer = Color(0xFF5C4131)
val DarkOnSecondaryContainer = Color(0xFFFFDCCB)
val DarkTertiary = Color(0xFFCBC9A0)
val DarkOnTertiary = Color(0xFF333100)
val DarkTertiaryContainer = Color(0xFF494825)
val DarkOnTertiaryContainer = Color(0xFFE7E5BB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A120C)
val DarkOnBackground = Color(0xFFF0DFD3)
val DarkSurface = Color(0xFF1A120C)
val DarkOnSurface = Color(0xFFF0DFD3)
val DarkSurfaceVariant = Color(0xFF52443B)
val DarkOnSurfaceVariant = Color(0xFFD6C3B6)
val DarkOutline = Color(0xFF9E8D81)
val DarkOutlineVariant = Color(0xFF52443B)
val DarkSurfaceDim = Color(0xFF1A120C)
val DarkSurfaceBright = Color(0xFF423730)
val DarkSurfaceContainerLowest = Color(0xFF140D07)
val DarkSurfaceContainerLow = Color(0xFF221B15)
val DarkSurfaceContainer = Color(0xFF261F19)
val DarkSurfaceContainerHigh = Color(0xFF312923)
val DarkSurfaceContainerHighest = Color(0xFF3C342D)
val DarkInverseSurface = Color(0xFFF0DFD3)
val DarkInverseOnSurface = Color(0xFF382E27)
val DarkInversePrimary = Color(0xFF9A4A00)
